#!/usr/bin/env bash
RELAY=${1:-wss://e.nos.lol}
## prices
nostril \
--sec $(mempool-space --blocks_tip_hash) \
--content "#mempool \

BLOCKS_TIP_HEIGHT=$(mempool-space --blocks_tip_height) \

USD=$(mempool-space_prices | gnostr-xq .USD) \

EUR=$(mempool-space_prices | gnostr-xq .EUR) \

GBP=$(mempool-space_prices | gnostr-xq .GBP) \

CAD=$(mempool-space_prices | gnostr-xq .CAD) \

CHF=$(mempool-space_prices | gnostr-xq .CHF)" \
--tag blocks_tip_height $(mempool-space --blocks_tip_height) \
-t gnostr | \
gnostr-post-event -r $RELAY
## fees
##fastestFee
nostril \
--sec $(mempool-space --blocks_tip_hash) \
--content "#mempool \

fastestFee: $(mempool-space_fees_recommended | gnostr-xq .fastestFee)" \
--tag blocks_tip_height $(mempool-space --blocks_tip_height) \
-t gnostr | \
gnostr-post-event -r $RELAY
##halfHourFee
nostril \
--sec $(mempool-space --blocks_tip_hash) \
--content "#mempool \

halfHourFee: $(mempool-space_fees_recommended | gnostr-xq .halfHourFee)" \
--tag blocks_tip_height $(mempool-space --blocks_tip_height) \
-t gnostr | \
gnostr-post-event -r $RELAY
