## #[source.crates-io]
## #replace-with = "vendored-sources"
##
## [source."git+https://github.com/gnostr-org/gnostr-bins.git"]
## git = "https://github.com/gnostr-org/gnostr-bins.git"
## replace-with = "vendored-sources"
##
## [source.vendored-sources]
## directory = "vendor"
