name: build/install-matrix

# Controls when the action will run.
on:
  schedule:
  - cron: '0 2 * * *' # run at 2 AM UTC¬
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build_and_install:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
          set-safe-directory: 'true'
      - name: printenv && brew install scdoc autoconf automake rustup-init libtool || sudo apt update && sudo apt install rustup-init scdoc -y
        run: |
          printenv && brew install scdoc autoconf automake rustup-init libtool || sudo apt update && sudo apt install rustup-init scdoc -y || true
      - name: cargo-binstall install gnostr-bins
        run: |
          cargo install cargo-binstall
          cargo-binstall install gnostr-bins
      - name: rm -rf deps
        run: |
          rm -rf deps
      - name: make
        run: |
          sudo mkdir -p /usr/local/share/man/man1 || true
          make
      - name: sudo make install
        run: |
          sudo make install
      - name: man nostril
        run: |
          sudo man nostril
      - name: sudo ./nostril
        run: |
          #pipe handles non-zero return from nostril default help
          file nostril
          sudo ./nostril --sec $(gnostr-sha256) --content "gnostr-chat:topic:$(git rev-parse HEAD)" -t $(gnostr-weeble) -t $(gnostr-blockheight) -t $(gnostr-wobble) -t gnostr-chat -t $(git rev-parse HEAD) | gnostr-post-event
          sudo ./nostril --sec $(gnostr-sha256) --content "gnostr-chat:topic:$(git rev-parse HEAD)" -t gnostr-chat -t $(git rev-parse HEAD) | gnostr-post-event
