name: nostril

on:
  push:
    branches: [ "master", "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: sudo make install
      run: |
        make
        sudo make install
    - name: man nostril
      run: |
        man nostril
    - name: nostril
      run: |
        nostril
