name: macos-release

# Controls when the action will run.
on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Import GPG Key
      - uses: crazy-max/ghaction-import-gpg@v1
        env:
        # https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: "build release"
        run: |
          brew install libtool autoconf automake
          printenv
          make
          shasum -a 256 nostril > nostril.sha256.txt
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.os }}
          prerelease: false
          title: "Release Build"
          files: |
            nostril
            nostril.sha256.txt
