name: deps

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nostcat:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        fetch-depth: 0
      - name: Restore deps
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        #if: ${{ !env.ACT }}
        with:
          path: |
            deps/git
            /root/.cargo
            /root/.rustup
          key: ${{ runner.os }}-deps

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: rustup
        run: printenv && sudo apt-get update && apt-get install -y python3 make autoconf automake libtool build-essential tclsh gettext git && touch ~/GH_ACT_TOKEN.txt

      #- name: submodule update
         #run: git submodule update --init --recursive

      - name: submodule update
        run: cargo install nostcat
      #- name: rustup default stable
         #run: rustup default stable && source "$HOME/.cargo/env" && make cargo-build cargo-install

      - name: Save deps
        id: cache-deps-save
        uses: actions/cache/save@v3
        #if: ${{ !env.ACT }}
        with:
          path: |
            deps/git
            /root/.cargo
            /root/.rustup
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

