name: ubuntu-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        fetch-depth: 0
      - name: Restore deps
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        #if: ${{ !env.ACT }}
        with:
          path: |
            deps
            /var/cache/apt
          key: ${{ runner.os }}-deps

      - name: touch ~/GH_ACT_TOKEN.txt
        run: |
          touch ~/GH_ACT_TOKEN.txt
          echo ${{ secrets.GITHUB_TOKEN }} > ~/GH_ACT_TOKEN.txt

      - name: apt-get_install
        run: |
          printenv && sudo apt-get update && \
          apt-get install -y python3 make autoconf automake libtool build-essential tclsh gettext
      - name: make submodules
        run: |
          make submodules

      - name: deps/secp256k1
        run: cd deps/secp256k1 && ./configure --disable-shared --enable-module-ecdh --enable-module-schnorrsig --enable-module-extrakeys && make install && cd ..

      - name: make nostril install
        run: |
          make nostril install

      - name: 0
        run: KEY=$(nostril --hash 0) && nostril --sec "$KEY" --envelope --content "gnostr is passing the ubuntu-matrix CI!"

      - name: 1
        run: KEY=$(nostril --hash 1) && nostril --sec "$KEY" --envelope --content "gnostr is passing the ubuntu-matrix CI!"

      - name: Save deps
        id: cache-deps-save
        uses: actions/cache/save@v3
        #if: ${{ !env.ACT }}
        with:
          path: |
            deps
            /var/cache/apt
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

