name: ubuntu-pre-release

# Controls when the action will run.
on:
  push:
    branches:
      - 'master'
      - '**pre-release**'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-release:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: "printenv"
        run: |
          printenv
          UNAME_M=$(echo uname -m)
          export UNAME_M
          echo $UNAME_M
      - name: "Build pre-release" ${{ matrix.os }}-$(echo uname -m)
        run: |
          make
          cp nostril nostril-$UNAME_M
          shasum -a 256 nostril-$UNAME_M > nostril-$UNAME_M.sha256.txt
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.os }}-$(echo uname -m)
          prerelease: true
          title: "Development Build" ${{ matrix.os }}-$(echo uname -m)
          files: |
            nostril-$UNAME_M
            nostril-$UNAME_M.sha256.txt
